[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
test = "RjBTVAA8PvLu2syA5yHEizEX3658pwJ67z7vwVreEjt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
